### PR TITLE
Add autoFocus prop

### PR DESCRIPTION
**Pull request by AlithAnar**
New autoFocus prop for search input.

It adds ref to input and trigger .focus() on compnent mount.

### CODE REVIEW

**Comment by bashkos** [comment]
Great job, really thanks, and sorry for waiting. One moment, I'm not sure about `setImmediate` method, it looks like non-standard. Can we avoid using it?

**Comment by AlithAnar** [comment]
> Great job, really thanks, and sorry for waiting. One moment, I'm not sure about `setImmediate` method, it looks like non-standard. Can we avoid using it?

Hi, in React ref to a component is available immediately after its componentDidMount method is called. The input element is not ready to be focused in that case. The workaround is using a timer function to be able to focus input.

You could use autoFocus prop on <input /> but its not reliabe in all cases.

> autofocus is easy to use but only works when the <input> is initially rendered; since React intelligently only re-renders elements that have changed, the autofocus attribute isn't reliable in all cases.

**Comment by bashkos** [comment]
Sorry for waiting :( Yeah, I understand, but this is really serious:

> Non-standard
This feature is non-standard and is not on a standards track. Do not use it on production sites facing the Web: it will not work for every user. There may also be large incompatibilities between implementations and the behavior may change in the future.

> This method is not expected to become standard, and is only implemented by recent builds of Internet Explorer and Node.js 0.10+. It meets resistance both from Gecko (Firefox) and Webkit (Google/Apple).

https://developer.mozilla.org/en-US/docs/Web/API/Window/setImmediate

And this https://caniuse.com/#feat=mdn-api_window_setimmediate

Maybe we can use `setTimeout(..., 0)` instead?

**Comment by AlithAnar** [comment]
Yes :) setTimeout is good aswell. I'll fix that

**Comment by AlithAnar** [comment]
Fixed

**Comment by bashkos** [comment]
Thanks for your job :)

**Pull request merged**
